on:
    push:
        branches:
            - master
        paths:
            - sh-thunk.js
            - sh-thunk.d.ts
            - package.json

jobs:
    prerelease:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Make prerelease to npm
              uses: epeli/npm-release@v1
              with:
                  type: prerelease
                  token: ${{ secrets.NPM_TOKEN }}
